# Generated by Django 4.0.1 on 2022-01-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=100)),
                ('econtact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
